### PR TITLE
fix: converters now uses naming-convention

### LINKED ISSUE #596: class-name convert deprecated. Rename to naming-convention
It's ot actually missing, but rule name is out of date.
[typescript-eslint issue with explaination](https://github.com/typescript-eslint/typescript-eslint/issues/1854#issuecomment-609913921)
I've a PR, so you can let me know when you accept it and I'll submit.

### 💥 Missing Converter

-   `tslint-to-eslint-config` version: latest
-   `typescript-eslint` version: 3.0.2

#### TSLint Rule Name

**class-name**

### PR DESCRIPTION
**Pull request by KingDarBoja**
## PR Checklist

-   [x] Addresses an existing issue: fixes #596
-   [x] That issue was marked as [`status: accepting prs`](https://github.com/typescript-eslint/tslint-to-eslint-config/labels/status%3A%20accepting%20prs)

## Overview

This should bring the latest changes from typescript-eslint (the rule removals section) as requested but not sure if I have to provide a merger for these converters @JoshuaKGoldberg

### CODE REVIEW

**Comment by KingDarBoja** [comment]
Also related to this issue at [typescrip-eslint](https://github.com/typescript-eslint/typescript-eslint/issues/2251).

File: src/rules/converters/class-name.ts [hunk 1]
```diff
@@ -4,7 +4,7 @@ export const convertClassName: RuleConverter = () => {
     return {
         rules: [
             {
-                ruleName: "@typescript-eslint/class-name-casing",
+                ruleName: "@typescript-eslint/naming-convention",
```
Comment (JoshuaKGoldberg) [inline src/rules/converters/class-name.ts:7]: [TSLint's `class-name`](https://palantir.github.io/tslint/rules/class-name) only allows PascalCase class names. Reading through the `naming-convention` source, I'm not seeing anything that defaults class names to any particular case: PascalCase or otherwise. That means this'll need some rule options to replicate the old behavior, right?

File: src/rules/converters/interface-name.ts [hunk 2]
```diff
@@ -4,7 +4,7 @@ export const convertInterfaceName: RuleConverter = () => {
     return {
         rules: [
             {
-                ruleName: "@typescript-eslint/interface-name-prefix",
+                ruleName: "@typescript-eslint/naming-convention",
```
Comment (JoshuaKGoldberg) [inline src/rules/converters/interface-name.ts:7]: Similar to `class-name`, [TSLint's `interface-name`](https://palantir.github.io/tslint/rules/interface-name/) specifies a default behavior -- and I'm thinking this converter is actually already buggy (at least per docs, if not in reality) because `interface-name`'s docs says it requires one of either `"always-prefix"` or "`never-prefix`".

File: src/rules/converters/class-name.ts (hunk 1 above)
Comment (KingDarBoja) [reply src/rules/converters/class-name.ts:7]: Based on the docs, the [`default` selector](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/naming-convention.md#group-selectors) matches everything but it is marked as camelCase, so you got a point here.

File: src/rules/converters/interface-name.ts (hunk 2 above)
Comment (KingDarBoja) [reply src/rules/converters/interface-name.ts:7]: Same as above comment, I will take a look this weekend :)

File: src/rules/converters/class-name.ts (hunk 1 above)
Comment (KingDarBoja) [reply src/rules/converters/class-name.ts:7]: @JoshuaKGoldberg Actually, the PascalCase for Classes and Interfaces is set as default. Checkout https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/src/rules/naming-convention.ts#L331 and the docs at [options](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/naming-convention.md#options) (scroll down a bit).

File: src/rules/converters/interface-name.ts (hunk 2 above)
Comment (KingDarBoja) [reply src/rules/converters/interface-name.ts:7]: This one is easy, there is an example at the end of the docs: https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/naming-convention.md#enforce-that-interface-names-do-not-begin-with-an-i

Comment (JoshuaKGoldberg) [reply src/rules/converters/interface-name.ts:7]: Well, sweet.
