### PR TITLE
Fix @typescript-eslint disable rules.

### LINKED ISSUE #1091: Missing ESLint rule disable in @typescript-eslint rule converter(s)
### 🐛 Bug Report

-   `tslint-to-eslint-config` version: 2.4.2
-   ESLint version: -
-   Node version: -

#### Actual Behavior

This issue was created according to this comment: <https://github.com/typescript-eslint/tslint-to-eslint-config/pull/1085#issuecomment-846487277>.

There are [@typescript-eslint/...](https://github.com/typescript-eslint/typescript-eslint) rules that require to turn off their `ESLint` counterpart like this:

```jsonc
{
  // note you must disable the base rule as it can report incorrect errors
  "no-use-before-define": "off",
  "@typescript-eslint/no-use-before-define": ["error"]
}
```
Source: <https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-use-before-define.md>

In the rule [convertNoUseBeforeDeclare](https://github.com/typescript-eslint/tslint-to-eslint-config/blob/main/src/converters/lintConfigs/rules/ruleConverters/no-use-before-declare.ts) this is not disabled.

Also I think it would be good to check all `@typescript-eslint` rule converters for this type of bug.

#### Expected Behavior

`@typescript-eslint` rule converters that require to turn off their `ESLint` rule counterpart actually turn them off.

### PR DESCRIPTION
**Pull request by Res42**
## PR Checklist

-   [X] Addresses an existing issue: fixes #1091
-   [X] That issue was marked as [`status: accepting prs`](https://github.com/typescript-eslint/tslint-to-eslint-config/labels/status%3A%20accepting%20prs)

## Overview

Fix converters for `@typescript-eslint` rules where the rule needs the base `ESLint` rule to be disabled.
Also added a sanity check test which *naively* searches for these rule pairs and fails if the base rule is not disabled.

### CODE REVIEW

File: src/converters/lintConfigs/rules/ruleConverters/align.ts [hunk 1]
```diff
@@ -29,6 +29,10 @@ export const convertAlign: RuleConverter = (tslintRule) => {
 
     return {
         rules: [
+            {
+                ruleName: "indent",
+                ruleSeverity: "off",
+            },
```
Comment (KingDarBoja) [inline src/converters/lintConfigs/rules/ruleConverters/align.ts:35]: Based on #149, I think it is safe to  update the [Typescript ESLint Roadmap](https://github.com/typescript-eslint/typescript-eslint/blob/61e035356ced5186040eb4aeb78bd74c1c1ce4b8/packages/eslint-plugin/ROADMAP.md) with this conversion. @JoshuaKGoldberg

**Review by KingDarBoja — APPROVED** [review]
Outstanding job! 🇭🇺

File: src/converters/lintConfigs/rules/meta.test.ts [hunk 2]
```diff
@@ -0,0 +1,84 @@
+import { promises as fs } from "fs";
+import { resolve, join } from "path";
+
+describe("@typescript-eslint rules that require another rule be disabled", () => {
```
Comment (JoshuaKGoldberg) [inline src/converters/lintConfigs/rules/meta.test.ts:4]: Err, I don't think this test needs to be written? A lot of the rules (e.g. `default-param-last`) weren't TSLint rulees and thus aren't relevant to this project. The rest are already tested in their own files.

**Review by JoshuaKGoldberg — CHANGES_REQUESTED** [review]
The rule converter fixes are EXCELLENT, thank you! But: I don't think the added test needs to be there?

File: src/converters/lintConfigs/rules/meta.test.ts (hunk 2 above)
Comment (Res42) [reply src/converters/lintConfigs/rules/meta.test.ts:4]: I written these so I could find the buggy rules and thought if I already written it, it can stay.
If/when a new conversion is added which forgets to disable a rule from here a test will break.

But if you want I will delete it.

**Review by JoshuaKGoldberg — APPROVED** [review]
Thanks! 💯
