### PR TITLE
rxjs-no-unsafe-takeuntil and fix in rxjs-no-async-subscribe

### LINKED ISSUE #790: rxjs-no-unsafe-takeuntil
### 💥 Missing Converter

-   `tslint-to-eslint-config` version: 1.5.0
-   `typescript-eslint` version: 4.6.0

#### TSLint Rule Name
[rxjs-no-unsafe-takeuntil](https://cartant.github.io/rxjs-tslint-rules/#rxjs-no-unsafe-takeuntil)

#### Package Source
rxjs-tslint-rules

### PR DESCRIPTION
**Pull request by criskrzysiu**
## PR Checklist

-   [x] Addresses an existing issue: fixes #790
-   [x] That issue was marked as [`status: accepting prs`](https://github.com/typescript-eslint/tslint-to-eslint-config/labels/status%3A%20accepting%20prs)

## Overview

adding rxjs-no-unsafe-takeuntil converter and fix in rxjs-no-async-subscribe converter (missing 'rxjs/' prefix in new rule name)
also added .idea (Webstorm/InteliJ) folder to .gitignore

### CODE REVIEW

File: src/converters/lintConfigs/rules/ruleConverters/eslint-plugin-rxjs/no-async-subscribe.ts [hunk 1]
```diff
@@ -4,7 +4,7 @@ export const convertNoAsyncSubscribe: RuleConverter = () => {
     return {
         rules: [
             {
-                ruleName: "no-async-subscribe",
+                ruleName: "rxjs/no-async-subscribe",
```
Comment (KingDarBoja) [inline src/converters/lintConfigs/rules/ruleConverters/eslint-plugin-rxjs/no-async-subscribe.ts:7]: Nice catch, I didn't saw that while reading the [ eslint-plugin-rxjs readme](https://github.com/cartant/eslint-plugin-rxjs) as I jumped right into the rule definition.

File: .gitignore [hunk 2]
```diff
@@ -11,3 +11,4 @@ test/*.js
 ~test/jest.config.js
 !test/tests/**/.eslintrc*
 !test/tests/**/*.log
+.idea/
```
Comment (KingDarBoja) [inline .gitignore:14]: I think this change would have been made in a separate issue as we should update the `.gitignore` file with more IDE / editors. 

cc @JoshuaKGoldberg

**Review by KingDarBoja — APPROVED** [review]
Overall the rule converter looks good to me, just waiting for @JoshuaKGoldberg opinion about the `gitignore` change.

File: src/converters/lintConfigs/rules/ruleConverters/eslint-plugin-rxjs/no-async-subscribe.ts (hunk 1 above)
Comment (criskrzysiu) [reply src/converters/lintConfigs/rules/ruleConverters/eslint-plugin-rxjs/no-async-subscribe.ts:7]: Same for me, I think that the doc is a bit misleading in that regard, especially [Rules](https://github.com/cartant/eslint-plugin-rxjs#rules) as there is no "rxjs/" prefix there

File: .gitignore (hunk 2 above)
Comment (JoshuaKGoldberg) [reply .gitignore:14]: Agreed 😄. @criskrzysiu do you want to send that in a separate PR? Otherwise / if you don't have the time one of us can remove it from here & send it too.

Comment (criskrzysiu) [reply .gitignore:14]: I will split it, np :)

Comment (criskrzysiu) [reply .gitignore]: @JoshuaKGoldberg  @KingDarBoja  reverted  .gitignore

**Review by JoshuaKGoldberg — APPROVED** [review]
Super, thanks!
