### PR TITLE
Used JSON5 for config file parsing

### LINKED ISSUE #742: Allow JSON5 features such as trailing commas in editor configs
This issue is related to https://github.com/typescript-eslint/tslint-to-eslint-config/issues/407

### 🐛 Bug Report

-   `tslint-to-eslint-config` version: 1.5.0
-   ESLint version: ^7.10.0
-   Node version: 12.18.3

#### Actual Behavior
`tslint-to-eslint-config` overwrite's entire `.vscode/settings.json` with an empty config if there is a trailing comma

##### With trailing comma
```diff
diff --git a/.vscode/settings.json b/.vscode/settings.json
index 44f8082..ca2996c 100644
--- a/.vscode/settings.json
+++ b/.vscode/settings.json
@@ -1,3 +1,14 @@
-{
-    "editor.formatOnSave": true,
-}
+/*
+👋 Hi! This file was autogenerated by tslint-to-eslint-config.
+https://github.com/typescript-eslint/tslint-to-eslint-config
+
+It represents the closest reasonable ESLint configuration to this
+project's original TSLint configuration.
+
+We recommend eventually switching this configuration to extend from
+the recommended rulesets in typescript-eslint. 
+https://github.com/typescript-eslint/tslint-to-eslint-config/blob/master/docs/FAQs.md
+
+Happy linting! 💖
+*/
+{}
```

##### Without trailing comma
```diff
diff --git a/.vscode/settings.json b/.vscode/settings.json
index f89ed5f..1eadf3f 100644
--- a/.vscode/settings.json
+++ b/.vscode/settings.json
@@ -1,3 +1,16 @@
+/*
+👋 Hi! This file was autogenerated by tslint-to-eslint-config.
+https://github.com/typescript-eslint/tslint-to-eslint-config
+
+It represents the closest reasonable ESLint configuration to this
+project's original TSLint configuration.
+
+We recommend eventually switching this configuration to extend from
+the recommended rulesets in typescript-eslint. 
+https://github.com/typescript-eslint/tslint-to-eslint-config/blob/master/docs/FAQs.md
+
+Happy linting! 💖
+*/
 {
     "editor.formatOnSave": true
 }
```

##### 1. The actual bug represented in this issue
It should accept trailing commas as they are valid in vscode configs.

##### 2. The bigger, not exactly this bug, but related problem:
It should not overwrite any settings in .vscode/* folder without an explicit option.

From the readme:
> The tslint-to-eslint-config command reads in any existing linter, TypeScript, and package configuration files, then creates an .eslintrc.js result based on them.

This does not indicate it's going to modify my editor files at all, only that it will create a new file, `.eslintrc.js`. **Please require an option/flag for any changes to editor configs!**

#### Reproduction

Add a trailing comma to your last item in your `.vscode/settings.json`, and run `tslint-to-eslint-config`, you'll see that it outputs an empty object.

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
## PR Checklist

-   [x] Addresses an existing issue: fixes #742
-   [x] That issue was marked as [`status: accepting prs`](https://github.com/typescript-eslint/tslint-to-eslint-config/labels/status%3A%20accepting%20prs)

## Overview

Quick replacement: instead of just `strip-json-comments`, uses the full JSON5 library to support fancy ECMAScript 5.1 features such as trailing commas.

### CODE REVIEW

File: src/utils.ts [hunk 1]
```diff
@@ -55,4 +55,6 @@ export const uniqueFromSources = <T>(...sources: (T | T[] | undefined)[]) => {
     return Array.from(new Set(items));
 };
 
-export const parseJson = (text: string) => JSON.parse(stripJsonComments(text));
+export const parseJson = (text: string) => JSON5.parse(text);
+
+console.log("HI", parseJson(`{ /* hi */ "wat": true }`));
```
Comment (KingDarBoja) [inline src/utils.ts:60]: Testing stuff? ;)

Comment (JoshuaKGoldberg) [reply src/utils.ts]: 🙈 my secret is revealed...!

**Review by KingDarBoja — APPROVED** [review]
