### PR TITLE
fix: Do not show Errors from reading directories

### LINKED ISSUE #1720: --comments throws EISDir when a directory is specified in TSConfig include
### 🐛 Bug Report

-   `tslint-to-eslint-config` version: 2.14.0
-   ESLint version: n/a
-   Node version: v20.2.0 (n/a)

#### Actual Behavior

```plaintext
$ npx tslint-to-eslint-config --comments

✨ 1 rule replaced with its ESLint equivalent. ✨

❗ 1 ESLint rule behaves differently from its TSLint counterpart ❗
  Check ./tslint-to-eslint-config.log for details.

⚡ 5 new packages are required for this ESLint configuration. ⚡
  npm install @typescript-eslint/eslint-plugin @typescript-eslint/parser eslint eslint-config-prettier eslint-plugin-prefer-arrow --save-dev
❌ 1 error running tslint-to-eslint: ❌
  Error: EISDIR: illegal operation on a directory, read
```

#### Expected Behavior

Shouldn't crash.

#### Reproduction

```shell
mkdir cool
touch cool/index.ts
```

```jsonc
// tsconfig.json
{
  "include": ["cool"]
}
```

As reported by @hyperupcall in #1717.

### PR DESCRIPTION
**Pull request by hyperupcall**
## PR Checklist

-   [x] Addresses an existing issue: fixes #1720
-   [x] That issue was marked as [`status: accepting prs`](https://github.com/typescript-eslint/tslint-to-eslint-config/labels/status%3A%20accepting%20prs)

## Overview

If a `tsconfig.json` contains something like the following:

```ts
{
    "include": ["cool"]
}
```

Then, an error shows up, for example, when using `--comments`:

```text
✨ 143 rules replaced with their ESLint equivalents. ✨

⚡ 1 new package is required for this ESLint configuration. ⚡
  npm install eslint-config-prettier --save-dev
❌ 1 error running tslint-to-eslint: ❌
  Error: EISDIR: illegal operation on a directory, read
```

According to the [TypeScript docs](https://www.typescriptlang.org/tsconfig#include), a directory entry for `include` is valid:

> If the last path segment in a pattern does not contain a file extension or wildcard charater, then it is treated as a directory, and files with supported extensions inside that directory are included (e.g. .ts, .tsx, and .d.ts by default, with .js and .jsx if [allowJs](https://www.typescriptlang.org/tsconfig#allowJs) is set to true).

This fixes that case.

### CODE REVIEW

File: src/converters/comments/convertFileComments.ts [hunk 1]
```diff
@@ -16,6 +16,10 @@ export const convertFileComments = async (
 ) => {
     const fileContent = await dependencies.fileSystem.readFile(filePath);
     if (fileContent instanceof Error) {
+        if (fileContent.code === "EISDIR") {
+            return undefined;
+        }
```
Comment (JoshuaKGoldberg) [inline src/converters/comments/convertFileComments.ts:21]: [Structure] I actually think the approach here isn't what I'd prefer. `collectCommentFileNames` is taking in a `typescriptConfiguration` that looks like:

```json
{
  "compilerOptions": { "target": "es3" },
  "files": ["./cool/index.ts"],
  "include": ["cool"]
}
```

...but with an output `commentFileNames` like:

```js
{
  exclude: undefined,
  include: [ './cool/index.ts', 'cool' ]
}
```

(note that the original TSConfig that made that is just `{ "include": ["cool"] }`. 

I think the right approach to fix this earlier in the system would be to have **`collectCommentFileNames`** filter out directories from its output. Or maybe just not use the `"include"` at all, if `files` has the full list of files?

What do you think?

**Review by JoshuaKGoldberg — CHANGES_REQUESTED** [review]
This works well (yay! thanks!) but I think I'd rather have the issue fixed closer to its source. What do you think?

I'm not against merging as-is if you think what's currently in the PR is a better approach, especially since this repo is old and relatively inactive.

File: src/converters/comments/convertFileComments.ts (hunk 1 above)
Comment (hyperupcall) [reply src/converters/comments/convertFileComments.ts]: That sounds good - I changed things so `collectCommentFileNames` handled the filtering of directories

File: src/adapters/fsFileSystem.ts [hunk 2]
```diff
@@ -11,6 +11,14 @@ export const fsFileSystem: FileSystem = {
             return false;
         }
     },
+    directoryExists: async (filePath: string) => {
+        try {
+            const stat = await fs.promises.stat(filePath);
+            return stat.isDirectory();
+        } catch (error) {
```
Comment (JoshuaKGoldberg) [inline src/adapters/fsFileSystem.ts:18]: Nit:

```suggestion
        } catch {
```

File: src/comments/collectCommentFileNames.ts [hunk 3]
```diff
@@ -26,12 +28,27 @@ export const collectCommentFileNames = async (
...
+        const includeListFiles = (
+            await Promise.all(includeList.map(dependencies.fileSystem.directoryExists))
+        )
+            .map((isDirectory, i) => {
+                if (isDirectory) {
+                    return null;
+                }
+                return includeList[i];
+            })
+            .filter((item): item is string => typeof item === "string");
```
Comment (JoshuaKGoldberg) [inline src/comments/collectCommentFileNames.ts:47]: Nit: there's a util for this already:

```suggestion
            .filter(isTruthy);
```

File: src/comments/collectCommentFileNames.ts [hunk 4]
```diff
@@ -26,12 +28,27 @@ export const collectCommentFileNames = async (
...
+        // Errors as they'll be handled when reading the file.
+        const includeListFiles = (
+            await Promise.all(includeList.map(dependencies.fileSystem.directoryExists))
+        )
+            .map((isDirectory, i) => {
+                if (isDirectory) {
+                    return null;
+                }
+                return includeList[i];
+            })
```
Comment (JoshuaKGoldberg) [inline src/comments/collectCommentFileNames.ts:46]: Nit: could one-line this if you really wanted 😄 

```suggestion
            .map((isDirectory, i) => !isDirectory && includeList[i])
```

**Review by JoshuaKGoldberg — APPROVED** [review]
Swell, thanks! This is looking great - and I appreciate you refactoring the internals. 🙌 

I'll apply a couple of nits that honestly don't really change much.

**Comment by JoshuaKGoldberg** [comment]
Oh, I don't have permissions to modify your fork. No worries - it's just nits.

**Comment by JoshuaKGoldberg** [comment]
Published in `tslint-to-eslint-config@2.14.1`. Thanks @hyperupcall! 🥳
